# Generated by Django 2.2.6 on 2021-12-03 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_follow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
